name: Run Robot Framework Tests
#Run jobs for push-events, for pull requests and scheduled:
on:
  push:
    branches:
      - master
    paths:
      - '!README.md'
  pull_request:
    paths:
      - '!README.md'
  schedule:
    - cron:  '0 0 1 1 *'  #once a year in January 1st
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Run Robot Framework Tests
          run: |
            docker run \
              -v ${PWD}/reports:/opt/robotframework/reports:Z \
              -v ${PWD}/tests:/opt/robotframework/tests:Z \
              -e ROBOT_OPTIONS="--variable DINOSAUR:Achillobator --variable NOT_DINOSAUR:kissa" \
              --user $(id -u):$(id -g) \
              ppodgorsek/robot-framework:latest
        - name: Upload reports
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
        - name: Send test report as comment to commit
          uses: joonvena/robotframework-reporter-action@v0.1
          if: ${{ github.event_name == 'push' }}
          env:
            GH_ACCESS_TOKEN: ${{ github.TOKEN }}
            REPO_OWNER: ${{ github.REPOSITORY_OwNER }}
            COMMIT_SHA: ${{ github.SHA }}
            REPOSITORY: ${{ secrets.REPO_NAME }}
            REPORT_PATH: ${{ github.workspace }}/reports
